server:
    port: 8081

spring:
    main:
        allow-bean-definition-overriding: true
    banner:
        image:
            location: classpath:banner.png
    data:
	mongodb:
	    uri: mongodb://localhost:9090/flights_travel_db?readPreference=secondaryPreferred

executorThreadPool:
    max_queue_capacity: 200
    max_pool_size: 50

redis:
    host: localhost
    port: 6379
    read_timeout: 3
    connect_timeout: 5
    min_idle: 5
    max_idle: 10
    max_total: 20
    max_wait_in_ms: 10000
    block_when_exhausted: false

client:
    username: TESTPAYTM
    password: Paytm@2019
    endpoint: https://6etestr4xapi.navitaire.com/
    domain_code: WWW
    agent_code: AG
    carrier_code: 6E

indigo:
    max_combination: 60
    time_between_connecting_flights_in_millis: 14400000
    infant_ssr_domestic_fee: 1250.0
    infant_ssr_domestic_tax: 0.0
    infant_ssr_international_fee: 2350.0
    infant_ssr_international_tax: 0.0
    non_refundable_taxes: YQ,RCF,BKF,PHF
    enabled_fare_classes: R,Z
    enabled_cabin_classes: economy
    handbaggage_product_classes: B
    discounted_rt_productclasses: N
    regular_product_classes: R,S,A,N,J
    show_combined_result_in_non_combined: true

session:
  key: indigo_client_signature
  timeout: 100000

